# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title visible in the browser and in search engine results.', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='The slug will be used as URL of the page. Must be unique!', max_length=200, unique=True, verbose_name='URL Slug')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='event date')),
                ('description', models.CharField(help_text='Short description of the page.', max_length=200, verbose_name='Short description')),
                ('sorting_value', models.IntegerField(default=0)),
            ],
        ),
    ]
