# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180427_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='sorting_value',
            field=models.IntegerField(default=0),
        ),
    ]
