# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-17 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventimage_sorting_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Short description of the event.', max_length=200, verbose_name='Short description'),
        ),
    ]
