# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, help_text='Show page in website top navigation menu.', verbose_name='Show in navigation'),
        ),
    ]
