# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_show_in_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_icon',
            field=models.CharField(blank=True, help_text='Enter a Font Awesome class name for the icon in navigation, e.g. "fa fa-info". See all icons here: http://fontawesome.io/icons/', max_length=200, null=True, verbose_name='Font Awesome icon class'),
        ),
    ]
