# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_mobile_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
