# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0001_initial'),
        ('accounts', '0003_auto_20170620_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='educational_need',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_need.EducationalNeed'),
        ),
    ]
