# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 19:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
