# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-17 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170911_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unconfirmed_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
