# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-18 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_unconfirmed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=3),
        ),
    ]
