# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0003_auto_20170628_2238'),
        ('accounts', '0006_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_educational_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educational_need.EducationalNeed'),
        ),
    ]
