# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_active_educational_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active_educational_need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_need.EducationalNeed'),
        ),
    ]
