# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 22:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20171203_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use only numeric characters.', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
