# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 19:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20171203_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use only numeric characters.', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use only numeric characters.', regex='^[0-9]*$')]),
        ),
    ]
