# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20171227_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization_area',
        ),
        migrations.AddField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
