# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-27 20:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20171227_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='profile_images', verbose_name='Profile image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use only numeric characters.', regex='^[0-9]*$')], verbose_name='Additional mobile number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='NGO/Organization name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Please use only numeric characters.', regex='^[0-9]*$')], verbose_name='Additional phone number'),
        ),
    ]
