# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171227_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Select this if you want to become a volunteer for Janani Care or other organization. You will receive email with instructions when we review your application.', verbose_name='I want to be a volunteer'),
        ),
    ]
