# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization_id',
            field=models.ForeignKey(blank=True, help_text='Only for volunteers. Select the organization you want to volunteer for as a volunteer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='Organization'),
        ),
    ]
