# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180329_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_id',
            field=models.ForeignKey(blank=True, help_text='Only for volunteers. Select the organization you want to work for as a volunteer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile', verbose_name='Organization'),
        ),
    ]
