# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180329_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='volunteer_cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='volunteer_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
