# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 23:12
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='announcement_images', verbose_name='Main image to be displayed on the list view.'),
        ),
    ]
