# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-17 22:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Main announcement content displayed on the detail view in rich text (can contain images etc...).', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.CharField(help_text='Short description of the announcement to be displayed on the list view.', max_length=200, verbose_name='Short description'),
        ),
    ]
