# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-04 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20181104_1827'),
        ('announcements', '0003_auto_20180617_2243'),
    ]

    operations = [
    ]
