# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational_need', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField(choices=[(0, 'Very bad'), (1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excelent')], default=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('educational_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_need.EducationalNeed')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
