# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0003_auto_20170727_0023'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='educational_need',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educational_need.EducationalNeed'),
        ),
    ]
