# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20170729_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Very bad'), (1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excelent')], default=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper', to=settings.AUTH_USER_MODEL),
        ),
    ]
