# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_remove_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Very bad'), (1, 'Bad'), (2, 'Average'), (3, 'Good'), (4, 'Very good'), (5, 'Excelent')], default=3),
        ),
    ]
