# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
