# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_comment_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rejected_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
