# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 22:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('college_school_address', models.TextField(blank=True, null=True)),
                ('college_school_contact_details', models.TextField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('amount_required', models.FloatField()),
                ('documents', models.FileField(upload_to='')),
                ('requirement_description', models.TextField()),
                ('communication_mode', models.CharField(choices=[('PH', 'Phone'), ('MO', 'Mobile'), ('EM', 'E-mail')], default='PH', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
