# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 21:44
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='additional_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='additional_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
