# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0002_educationalneed_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='title',
            field=models.CharField(default='This is a pretty long title just for testing', max_length=200),
            preserve_default=False,
        ),
    ]
