# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0002_auto_20170726_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='hide_mobile_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='hide_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
