# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-11 19:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0003_educationalneed_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalneed',
            name='requirement_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
