# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0003_auto_20170727_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
