# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0005_auto_20170801_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalneed',
            name='additional_mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
