# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0007_auto_20170912_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalneed',
            name='date_uuid',
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
    ]
