# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0011_auto_20170918_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalneed',
            name='hide_current_address',
            field=models.BooleanField(default=True),
        ),
    ]
