# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0012_auto_20170919_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
