# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-04 17:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_profile_multiple_needs'),
        ('educational_need', '0015_educationalneed_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalneed',
            name='ext_about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country'),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='profile_images', verbose_name="Person's picture"),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.State'),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='ext_zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='educationalneed',
            name='extended',
            field=models.BooleanField(default=False),
        ),
    ]
