# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-04 17:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('educational_need', '0016_auto_20181104_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalneed',
            name='ext_state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='ext_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.State'),
        ),
    ]
